
services:
  postgis:
#    profiles:
#      - postgis
    image: postgis/postgis:14-3.5
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statmagic
      DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ${PWD}/statmagic_dump.dump.out:/tmp/statmagic_dump.dump.out
      - ${PWD}/init_scripts:/docker-entrypoint-initdb.d/

    # configs:
    #   - source: init_db
    #     target: /docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "statmagic"]
      interval: "3s"
      timeout: "3s"
      retries: 30

#  postgis-migrate:
##    profiles:
##      - postgis
#    image: migrate/migrate:v4.17.0
#    depends_on:
#      postgis:
#        condition: service_healthy

  web-app:
    build:
      args:
        DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
        CDR_API_TOKEN: $CDR_API_TOKEN
      dockerfile: Dockerfile
    command: server
    volumes:
      - ./statmagic_000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./startup.sh:/usr/local/project/startup.sh
      - ./datalayer_download:/usr/local/project/datalayer_download
      - ./statmagic.map:/usr/local/project/statmagic.map
    ports:
      - 8000:80
    environment:
      CDR_API_TOKEN: $CDR_API_TOKEN
      DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      MAPSERVER_SERVER: $MAPSERVER_SERVER
      TILESERVER_LOCAL_SYNC_FOLDER: $TILESERVER_LOCAL_SYNC_FOLDER
    depends_on:
      postgis:
        condition: service_healthy

  cdr-sync:
    build:
      args:
        DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
        CDR_API_TOKEN: $CDR_API_TOKEN
      dockerfile: Dockerfile
    entrypoint: cron -f
    volumes:
      - ./datalayer_download:/usr/local/project/datalayer_download
      - ./statmagic.map:/usr/local/project/statmagic.map
    environment:
      CDR_API_TOKEN: $CDR_API_TOKEN
      DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      MAPSERVER_SERVER: $MAPSERVER_SERVER
      TILESERVER_LOCAL_SYNC_FOLDER: $TILESERVER_LOCAL_SYNC_FOLDER

  tileserver:
    build:
      dockerfile: Dockerfile_tileserver
    volumes:
      - ./datalayer_download:/datalayer_download
      - ./statmagic.map:/var/www/mapfiles/statmagic.map
      - ./symbols.sym:/var/www/mapfiles/symbols.sym
      - ./tileserver_000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8081:80

#    environment:
#

# configs:
#   init_db:
#     file: ./init.sql

volumes:
  postgis_data: