
services:
  postgis:
    profiles: [application]
    image: postgis/postgis:14-3.5
    container_name: statmagic-database
    user: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statmagic
      DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ${PWD}/statmagic_dump.dump.out:/tmp/statmagic_dump.dump.out
      - ${PWD}/init_scripts:/docker-entrypoint-initdb.d/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "statmagic"]
      interval: "3s"
      timeout: "3s"
      retries: 30

  web-app:
    profiles: [application]
    build:
      args:
        DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
        CDR_API_TOKEN: $CDR_API_TOKEN
      dockerfile: statmagic.Dockerfile
    image: efvega/statmagic-web-app
    container_name: statmagic-web-app
    command: server
    hostname: statmagic-web-app
    restart: always
    volumes:
      - ./datalayer_download:${TILESERVER_LOCAL_SYNC_FOLDER}
      - ./statmagic.map:/var/www/mapfiles/statmagic.map
    ports:
      - "8000:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      postgis:
        condition: service_healthy

  cdr-sync:
    profiles: [tile]
    image: efvega/statmagic-web-app
    container_name: statmagic-cdr-sync
    entrypoint: cron -f
    restart: always
    volumes:
      - ./datalayer_download:${TILESERVER_LOCAL_SYNC_FOLDER}
      - ./statmagic.map:/var/www/mapfiles/statmagic.map
    env_file:
      - .env

  tileserver:
    profiles: [tile]
    build:
      dockerfile: tileserver.Dockerfile
      args:
        WEBAPP_HOSTNAME: $WEBAPP_HOSTNAME
    image: efvega/statmagic-tileserver
    container_name: statmagic-tileserver
    restart: always
    volumes:
      - ./datalayer_download:/usr/local/project/datalayer_download
      - ./statmagic.map:/var/www/mapfiles/statmagic.map
      - ./symbols.sym:/var/www/mapfiles/symbols.sym
      - ./tileserver_000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8081:443"

#  beak-som:
#    profiles: [beak]
#    build:
#      dockerfile: beak.Dockerfile
#    image: efvega/beak-som
#    container_name: beak-som
#    restart: always
#    ports:
#      - "9999:9999"
#    env_file:
#      - beak.env

volumes:
  postgis_data: