
services:
  postgis:
#    profiles:
#      - postgis
    image: postgis/postgis:14-3.5
    user: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statmagic
      DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ${PWD}/statmagic_dump.dump.out:/tmp/statmagic_dump.dump.out
      - ${PWD}/init_scripts:/docker-entrypoint-initdb.d/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "statmagic"]
      interval: "3s"
      timeout: "3s"
      retries: 30

#  postgis-migrate:
##    profiles:
##      - postgis
#    image: migrate/migrate:v4.17.0
#    depends_on:
#      postgis:
#        condition: service_healthy

  web-app:
    build:
      args:
        DJANGO_USER_STATMAGIC_PGPASS: $DJANGO_USER_STATMAGIC_PGPASS
        CDR_API_TOKEN: $CDR_API_TOKEN
      dockerfile: Dockerfile
    command: server
    restart: always
    volumes:
      - ./statmagic_000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./startup.sh:/usr/local/project/startup.sh
      - ./datalayer_download:${TILESERVER_LOCAL_SYNC_FOLDER}
      - ./statmagic.map:/usr/local/project/statmagic.map
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      postgis:
        condition: service_healthy

  cdr-sync:
    image: mtri-statmagic-deploy-web-app
    depends_on:
      - web-app
    entrypoint: cron -f
    restart: always
    volumes:
      - ./datalayer_download:${TILESERVER_LOCAL_SYNC_FOLDER}
      - ./statmagic.map:/usr/local/project/statmagic.map
    env_file:
      - .env

  tileserver:
    build:
      dockerfile: Dockerfile_tileserver
    restart: always
    volumes:
      - ./datalayer_download:/usr/local/project/datalayer_download
      - ./statmagic.map:/var/www/mapfiles/statmagic.map
      - ./symbols.sym:/var/www/mapfiles/symbols.sym
      - ./tileserver_000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8081:80

volumes:
  postgis_data: